#基于 Docker 来安装 Nginx
version: '3.1'
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./wwwroot:/usr/share/nginx/wwwroot


  tomcat1:
    image: tomcat:8.5
    container_name: tomcat1
    ports:
      - 9090:8080

  tomcat2:
    image: tomcat:8.5
    container_name: tomcat2
    ports:
      - 9091:8080
