#  1、 YAML基本语法
#        – 使用缩进表示层级关系
#        – 缩进时不允许使用Tab键，只允许使用空格。
#        – 缩进的空格数目不重要，只要相同层级的元素左侧对齐即可
#        – 大小写敏感
#  2、 YAML 支持的三种数据结构
#        – 对象：键值对的集合
#        – 数组：一组按次序排列的值
#        – 字面量：单个的、不可再分的值


person:
    lastname: 山羊
    age: 15
    boss: false
#    birth: 2017-12-11  sos 这种时间格式 会报错！
    birth: 2017/12/11
    maps: {k1: v1,k2: v2}
    lists: [lisi,wangwu,zhaoliu]  # 数组 行内写法
    pet: {nickName: 童童,age: 11} # 对象 行内写法


#  ""：双引号；不会转义字符串里面的特殊字符；特殊字符会作为本身想表示的意思
  #    name:   "zhangsan \n lisi"：输出；zhangsan 换行  lisi
#  ''：单引号；会转义特殊字符，特殊字符最终只是一个普通的字符串数据
  #    name:   ‘zhangsan \n lisi’：输出；zhangsan \n  lisi

student:
  name: shanyang
  age: 23
  sex: true
  bir: 2019/02/12
  location: {pro: 陕西,city: 西安,area: 雁塔区}
  hobbies:
    - 足球
    - 篮球
  skills: # 数组 行外写法 需要用 - 表示数组中的一个元素
    - 打架
    - 杀人
    - 放火
  pet:  # 对象 行外写法
    nickName: 童童
    age: 11










