

spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8777 # 指定SpringBootAdmin服务端地址


server:
  port: 8999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8542/eureka/  #注册中心地址
