

server:
  port: 8831

spring:
  rabbitmq:
    host: 192.168.235.207
    port: 5672
    username: guest
    password: guest
    publisher-returns: true  # 支持发布返回
    publisher-confirms: true # 支持发布确认
    virtual-host:  / # Invalid configuration: 'virtualHost' must be non-null