spring:
  rabbitmq:
    host: 192.168.235.207
    port: 5672
    username: guest
    password: guest
    publisher-returns: true  # 确认返回回调
    publisher-confirms: true # 启动确认回调
    virtual-host:  / # Invalid configuration: 'virtualHost' must be non-null
    listener:
      simple:
        acknowledge-mode: manual  #采用手动应答
        concurrency: 1     # 指定最小的消费者数量
        max-concurrency: 1 #  指定最大的消费者数量
        retry:
          enabled: true #  开启重试机制
          max-attempts: 2 #  重试次数 默认为 3
#      direct:
#        acknowledge-mode: manual #采用手动应答
    template:
      retry:
        enabled: true


server:
  port: 8831
