#spring:
#  output:
#    ansi:
#      enabled: always
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./config/

license:
  verify:
    resource: /publicKey.store
    storepass: init123
    alias: publickey
    subject: license
    license-path: ./license.lic
#    license-path: /license.lic
server:
  port: 3492