
mybatis:
  # 指定mybatis全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定mybatis sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.128:3306/quartz?characterEncoding=utf8
    username: root
    password: 12345









