spring:
  output:
    ansi:
      enabled: always

license:
  create:
    resource: /privateKey.store # 私钥库文件的地址，这里是classpath的地址
    keypass: init123    # 该密码是生成密钥对的密码，需要妥善保管，不能让使用者知道
    storepass: init123  # 该密码是在使用keytool生成密钥对时设置的密钥库的访问密码
    alias: privatekey
    subject: license
    license-path: ./license.lic  # 生成的license文件地址，这里是 springboot 根目录了。。。。。
#    not-after: 2019-10-1  # 截止日期 sos 该时间必须要超过 当天日期 否则 无法生成  license.lic

    not-before: 2018-12-21  #从2018-xx-xx开始
    not-after: 2019-03-01  # 截止到2018-xx-xx为止的前一天
    issued-time: 2018-12-21  # 发布时间
#    consumer-amount: 1  # 消费者数量  默认
server:
  port: 3491





