# dubbo服务发布者实现类注解@service所在的包  sos 这里注意： 包扫描的是  service 的上一层

dubbo:
  scan:
    basePackages: com.goat
  application:
    id: service-consumer
    name: service-consumer
  protocol:
    id: dubbo
    name: dubbo
    serialization: kryo

  registry:
    id: zookeeper
    address: zookeeper://172.16.163.135
#    address: zookeeper://47.98.148.84 # 注册到 阿里云的 zookeeper
#    address: zookeeper://172.16.71.34  # 注册到 阿里云的 内网id zookeeper
    port: 2181

  consumer:
    loadbalance: roundrobin

