# ES
#spring:
#  data:
#    elasticsearch:
#      cluster-nodes: 192.168.136.128:9300
#      repositories: true
#spring:
#  elasticsearch:
#    jest:
#      uris: http://192.168.136.128:9200

#server:
#  port: 8731

