# ES
#spring:
#  data:
#    elasticsearch:
#      cluster-nodes: 172.16.163.135:9300
#      repositories: true
#spring:
#  elasticsearch:
#    jest:
#      uris: http://172.16.163.135:9200

#server:
#  port: 8731

