spring:
  data:
    mongodb:
      host: 172.16.163.135
      port: 27017
#    sos  如果 mongodb 是以 账号密码 方式启动  才需要加 下面的 属性， 若是不需要授权方式启动 则 不能加下面的属性 否则 报错 未授权。。。
#      database: admin
#      username: root
#      password: mongo